name: Test
on:
  push:
    branches:
      - '**'

permissions:
  packages: none

jobs:

  editorconfig-checker:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0 # same as ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0 # same as 0527b11555ed46afd00df746f35b79cb7f7b68c2

      - name: Main test code
        shell: bash
        run: |
          RESULT=$(curl -V)
          echo $RESULT
          RESULT=RESULT=$(curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/merges \
              -d '{"base":"$BRANCH","head":"$REF"}')
          echo $RESULT
